# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mockuper}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edmagne Lira dos Santos"]
  s.date = %q{2012-05-30}
  s.default_executable = %q{mockuper}
  s.description = %q{Easy way to generate mockups}
  s.email = %q{edmagne@yahoo.com.br}
  s.executables = ["mockuper"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/mockuper",
    "defaults/TestNames.html",
    "defaults/core/css/style.css",
    "defaults/core/css/templates.css",
    "defaults/core/js/mockuper.js",
    "defaults/core/js/plugins.js",
    "defaults/core/json/lorem.json",
    "defaults/core/json/people.json",
    "defaults/templates/menu.html",
    "lib/mockuper.rb",
    "templates/c-f.html",
    "templates/c-rb.html",
    "templates/h-c-c-f.html",
    "templates/h-c-f.html",
    "templates/h-c-rb-f.html",
    "templates/h-c.html",
    "templates/h-clb-c-f.html",
    "templates/h-crb-c-f.html",
    "templates/h-lb-c-f.html",
    "templates/h-rb-c-f.html",
    "templates/lb-c.html",
    "templates/lb-h-c-f.html",
    "templates/rb-h-c-f.html",
    "test/helper.rb",
    "test/test_mockuper.rb"
  ]
  s.homepage = %q{http://github.com/edmagne/mockuper}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.0}
  s.summary = %q{Mockuper}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

